### ISSUE TITLE
font-family: 'Century Gothic'

### ISSUE THREAD

**Issue by sannevanseeventer** [CelinexPutte/connect-your-tribe-profile-card#3]
https://github.com/CelinexPutte/connect-your-tribe-profile-card/blob/dc61292d8c4c8f018c92e7759e1a61ba279251b6/public/style.css#L58

Zet achter je gekozen font: sans-serif, voor gebruikers die het lettertype niet hebben. 

`font-family: 'Century Gothic', sans-serif;`

**Comment by CelinexPutte** [comment]
Done
